name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: dotnet.yml
        name: artifact
    - name: Adding Execute Permission
      run: chmod -R 711 scripts/
    - name: Setup
      run: scripts/setup.sh
      shell: bash
      env:
        APP_SETTINGS: ${{secrets.APP_SETTINGS}}
    - name: Copy remote files
      uses: appleboy/scp-action@master
      with:
        host: sovize.com
        username: ${{secrets.REMOTE_USER}}
        key: ${{secrets.SSH_KEY}}
        passphrase: ${{secrets.SSH_FRASE}}
        source: deploy/*
        overwrite: true
        target: /var/www/flareApi
    - name: SSH Remote
      uses: appleboy/ssh-action@v0.1.4
      env:
        REMOTE_USER: ${{secrets.REMOTE_USER}}
      with:
        host: sovize.com
        username: ${{secrets.REMOTE_USER}}
        passphrase: ${{secrets.SSH_FRASE}}
        key: ${{secrets.SSH_KEY}}
        script_stop: true
        script: |
          echo "this is on the remote $REMOTE_USER $GITHUB_WORKFLOW $GITHUB_RUN_ID" > /var/www/flareApi/file.txt
          systemctl stop flare.service
          cd /var/www/flareApi
          rm -vf *.dll *.json FlareApi FlareApi.pdb
          rm -rfv runtimes/
          mv deploy/* .
          rmdir deploy/
          chmod -R 711 .
          chmod -R 644 *.json
          chown $REMOTE_USER:$REMOTE_USER
          systemctl start flare.service
        envs: REMOTE_USER,GITHUB_WORKFLOW,GITHUB_RUN_ID
