name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: dotnet.yml
        name: artifact
        path: build
    - name: Printing Fun
      run: scripts/setup.sh
      shell: bash
      env:
        APP_SETTINGS: ${{secrets.APP_SETTINGS}}
    
