name: CI

env:
  buildConfig: 'Release'
  Api: ' ./FlareApi/FlareApi.csproj'

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $Api
    - name: Build
      run: dotnet build $Api --no-restore -c $buildConfig
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish $Api --no-build -c $buildConfig -o ./artifact/deploy
    - name: Copy Script
      run: cp -r scripts/ artifact; ls artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: artifact
        path: 'artifact'
        retention-days: 31
