name: .NET

env:
  buildConfig: 'Release'
  runtime: 'ubuntu-x86'
  Api: ' ./FlareApi/FlareApi.csproj'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $Api -r $runtime
    - name: Build
      run: dotnet build $Api --no-restore -c $buildConfig -r $runtime --self-contained false
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish $Api --no-build -c $buildConfig -r $runtime -o deploy --self-contained false
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: artifact
        path: 'deploy'
        retention-days: 31
